# Generated by Django 5.1.2 on 2024-10-29 19:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='improved_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='original_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
